package com.householdops.app.shoppinglist;

import java.math.BigDecimal;
import java.util.UUID;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Positive;

public class ShoppingListDtos {

    public record ShoppingListItemResponse(
            UUID id,
            UUID householdId,
            UUID inventoryItemId,
            String description,
            int quantity,
            BigDecimal estimatedCost,
            ShoppingListItemStatus status,
            boolean autoGenerated,
            boolean approvalPending) {

        public static ShoppingListItemResponse from(ShoppingListItem item, boolean approvalPending) {
            return new ShoppingListItemResponse(
                    item.getId(),
                    item.getHousehold().getId(),
                    item.getInventoryItem() != null ? item.getInventoryItem().getId() : null,
                    item.getDescription(),
                    item.getQuantity(),
                    item.getEstimatedCost(),
                    item.getStatus(),
                    item.isAutoGenerated(),
                    approvalPending);
        }
    }

    public record CreateShoppingListItemRequest(
            @NotBlank String description,
            @Positive int quantity,
            BigDecimal estimatedCost,
            UUID inventoryItemId) {
    }

    public record UpdateShoppingListItemStatusRequest(ShoppingListItemStatus status) {
    }

    private ShoppingListDtos() {
    }
}
