package com.householdops.app.inventory;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.householdops.app.household.Household;
import com.householdops.app.household.HouseholdRepository;
import com.householdops.app.shoppinglist.ShoppingListService;

import lombok.RequiredArgsConstructor;

/**
 * Runs the XML-wired ReorderRulesEngine against every household's inventory,
 * queuing an auto-generated shopping list item for anything low on stock
 * that doesn't already have one pending. Runs on a schedule, but also
 * callable directly for the on-demand /shopping-list/generate endpoint so
 * the effect is demoable without waiting on the clock.
 */
@Component
@RequiredArgsConstructor
public class ReorderJob {

    private static final Logger log = LoggerFactory.getLogger(ReorderJob.class);

    private final HouseholdRepository householdRepository;
    private final InventoryRepository inventoryRepository;
    private final ShoppingListService shoppingListService;
    private final ReorderRulesEngine reorderRulesEngine;

    @Scheduled(fixedDelayString = "${app.reorder.interval-ms:300000}")
    @Transactional
    public void runForAllHouseholds() {
        for (Household household : householdRepository.findAll()) {
            runForHousehold(household);
        }
    }

    @Transactional
    public int runForHousehold(Household household) {
        List<InventoryItem> items = inventoryRepository.findByHouseholdId(household.getId());
        int queued = 0;

        for (InventoryItem item : items) {
            if (!reorderRulesEngine.needsReorder(item)) {
                continue;
            }
            if (shoppingListService.hasPendingAutoGeneratedItem(item.getId())) {
                continue;
            }

            int quantity = reorderRulesEngine.reorderQuantityFor(item);
            shoppingListService.createAutoGenerated(household, item, quantity);
            queued++;
        }

        if (queued > 0) {
            log.info("Reorder job queued {} shopping list item(s) for household {}", queued, household.getId());
        }
        return queued;
    }
}
