import { useGenerateReorderItems, useShoppingList, useUpdateShoppingListStatus } from '../hooks/useShoppingList'

export function ShoppingListPage() {
  const shoppingList = useShoppingList()
  const updateStatus = useUpdateShoppingListStatus()
  const generate = useGenerateReorderItems()

  const pending = shoppingList.data?.filter((item) => item.status === 'PENDING') ?? []
  const purchased = shoppingList.data?.filter((item) => item.status === 'PURCHASED') ?? []

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-slate-900">Shopping List</h1>
        <button
          onClick={() => generate.mutate()}
          disabled={generate.isPending}
          className="rounded border border-slate-300 px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          title="Runs the reorder-rules engine now, instead of waiting for its schedule"
        >
          {generate.isPending ? 'Checking inventory...' : 'Check inventory for restocks'}
        </button>
      </div>

      {shoppingList.isLoading && <p className="text-sm text-slate-500">Loading...</p>}

      <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
        <h2 className="mb-1 text-sm font-semibold text-slate-900">To buy</h2>
        {pending.length === 0 && <p className="py-2 text-sm text-slate-500">Nothing pending.</p>}
        <ul className="divide-y divide-slate-100">
          {pending.map((item) => (
            <li key={item.id} className="flex items-center justify-between gap-4 py-3">
              <div className="min-w-0">
                <p className="text-sm font-medium text-slate-900">
                  {item.description}
                  {item.autoGenerated && (
                    <span className="ml-2 rounded bg-blue-50 px-1.5 py-0.5 text-xs font-medium text-blue-700">auto-generated</span>
                  )}
                </p>
                <p className="text-xs text-slate-500">
                  Qty {item.quantity}
                  {item.estimatedCost != null && ` · $${item.estimatedCost}`}
                  {item.approvalPending && <span className="ml-1 font-medium text-amber-600">· Approval pending</span>}
                </p>
              </div>
              <button
                onClick={() => updateStatus.mutate({ id: item.id, status: 'PURCHASED' })}
                disabled={updateStatus.isPending}
                className="rounded border border-slate-300 px-2 py-1 text-xs text-slate-700 hover:bg-slate-50 disabled:opacity-50"
              >
                Mark purchased
              </button>
            </li>
          ))}
        </ul>
      </div>

      {purchased.length > 0 && (
        <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
          <h2 className="mb-1 text-sm font-semibold text-slate-900">Purchased</h2>
          <ul className="divide-y divide-slate-100">
            {purchased.map((item) => (
              <li key={item.id} className="py-2 text-sm text-slate-500 line-through">
                {item.description}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}
