export type StaffRole = 'OWNER' | 'HOUSE_MANAGER' | 'STAFF' | 'VENDOR'

export type TaskStatus = 'OPEN' | 'IN_PROGRESS' | 'BLOCKED' | 'DONE' | 'CANCELLED'

export type ShoppingListItemStatus = 'PENDING' | 'PURCHASED' | 'CANCELLED'

export type ApprovalStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED'

export type ApprovalSubjectType = 'TASK' | 'SHOPPING_ITEM'

export interface AuthResponse {
  accessToken: string
  refreshToken: string
  staffId: string
  householdId: string
  fullName: string
  role: StaffRole
}

export interface Household {
  id: string
  name: string
  address: string
  timezone: string
  principalUserId: string | null
  approvalThreshold: number
}

export interface StaffMember {
  id: string
  fullName: string
  email: string
  role: StaffRole
  householdId: string
  active: boolean
}

export interface HouseholdTask {
  id: string
  householdId: string
  title: string
  description: string | null
  assignedToId: string | null
  createdById: string
  status: TaskStatus
  dueDate: string | null
  estimatedCost: number | null
  linkedInventoryItemId: string | null
  approvalPending: boolean
}

export interface InventoryItem {
  id: string
  householdId: string
  name: string
  category: string
  currentQuantity: number
  unit: string
  reorderThreshold: number
  reorderQuantity: number
  lowStock: boolean
  lastRestockedAt: string | null
  vendorId: string | null
  vendorName: string | null
  unitCost: number | null
  totalValue: number | null
  expirationDate: string | null
  expiringSoon: boolean
  predictedDaysUntilEmpty: number | null
}

export interface InventoryStatus {
  householdId: string
  totalItems: number
  lowStockCount: number
  lowStockItems: InventoryItem[]
  expiringSoonItems: InventoryItem[]
  runningOutSoonItems: InventoryItem[]
}

export interface Vendor {
  id: string
  householdId: string
  name: string
  contactEmail: string | null
  contactPhone: string | null
  notes: string | null
}

export type AdjustmentReason = 'INITIAL' | 'RESTOCK' | 'CONSUMPTION' | 'MANUAL_CORRECTION'

export interface InventoryAdjustment {
  id: string
  inventoryItemId: string
  previousQuantity: number
  newQuantity: number
  delta: number
  reason: AdjustmentReason
  adjustedById: string | null
  adjustedByName: string | null
  occurredAt: string
}

export interface CategoryValuation {
  category: string
  totalValue: number
  itemCount: number
}

export interface ValuationResponse {
  householdId: string
  totalValue: number
  byCategory: CategoryValuation[]
}

export interface ImportResult {
  imported: number
  errors: string[]
}

export interface ShoppingListItem {
  id: string
  householdId: string
  inventoryItemId: string | null
  description: string
  quantity: number
  estimatedCost: number | null
  status: ShoppingListItemStatus
  autoGenerated: boolean
  approvalPending: boolean
}

export interface ApprovalRequest {
  id: string
  householdId: string
  requestedById: string
  principalId: string
  subjectType: ApprovalSubjectType
  subjectId: string
  amount: number
  justification: string | null
  status: ApprovalStatus
  decidedAt: string | null
  decisionNote: string | null
}

export interface PageResponse<T> {
  content: T[]
  totalElements: number
  totalPages: number
  number: number
  size: number
}

export interface AssistantToolCall {
  tool: string
  inputSummary: string
}

export interface AssistantQueryResponse {
  answer: string
  toolCalls: AssistantToolCall[]
}

export interface PropertySummary {
  householdId: string
  name: string
  address: string
  primary: boolean
  inventoryValue: number
  lowStockCount: number
  pendingApprovalCount: number
}

export interface PortfolioResponse {
  properties: PropertySummary[]
}
